Swappable Yield Source
pooltogether/swappable-yield-source pull request #1
Opened 2021-06-17 17:46 UTC by PierrickGT

Notion ticket with specs: https://www.notion.so/ptinc/Swappable-Yield-Source-e2e0327a424d440d82f1d15740a13db5

Todolist:
- [x] Write contract
- [x] Write deploy script
- [x] Write mainnet fork tests
- [x] Write unit tests
- [x] Setup Coverall workflow in Github Actions
- [x] Setup mainnet forking workflow in Github Actions

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  /// @notice Mock Initializer to prevent initialization by a third person right after deploying.
It's not to prevent initialization by third parties- it's to disable instances that are simply used as implementations for minimal proxies:

"Mock initializer to initialize implementations used by minimal proxies"

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    if (totalSupply() == 0) {
Refactor `totalSupply()` into a local var so that it's only called once (it's a public fxn so there is a premium to call it)

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    if (totalSupply() == 0) {
Let's pull totalSupply() into a variable here as well

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  function _isYieldSource(IYieldSource yieldSourceToCheck) internal {
Can we rename this to `_requireYieldSource` ? typically functions that begin with `isX` simply returned a boolean true or false value

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    IERC20Upgradeable _depositToken = IERC20Upgradeable(depositToken());
Let's call `yieldSource.depositToken()` here instead to save a little gas

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    require(newYieldSource != _oldYieldSource, "SwappableYieldSource/same-yield-source");
Need to also check that deposit tokens match here.

In which case- we can skip calling `_isYieldSource` to save gas, since we're calling those fxns anyway

2021-06-17 23:22 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  function transferFunds(address oldYieldSource, address newYieldSource, uint256 amount) external {
This function is public, so the caller should NOT be able to pass in the target yield source!  This is asking for a rug pull!

What would be better is to simply pass `yieldSource` and the `amount`.  The function will transfer from the passed yield source to the current one (if different)

2021-06-22 14:06 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  /// @notice Mock Initializer to prevent initialization by a third person right after deploying.
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/0e0a4913e0545fba1c8c28089734aecd25882d35

2021-06-22 14:06 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    if (totalSupply() == 0) {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/90c98c6b1b6a72ba65d4a4d14a25a86bd082951b

2021-06-22 14:06 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    if (totalSupply() == 0) {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/90c98c6b1b6a72ba65d4a4d14a25a86bd082951b

2021-06-22 14:06 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function _isYieldSource(IYieldSource yieldSourceToCheck) internal {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/9a8e0a97126b6e2e0bc03dff4369de78c7336059

2021-06-22 14:11 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    IERC20Upgradeable _depositToken = IERC20Upgradeable(depositToken());
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/e3df95b16fe5a4a95a394f75f0d103f03f5996ea

2021-06-22 14:11 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    require(newYieldSource != _oldYieldSource, "SwappableYieldSource/same-yield-source");
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/58772a3fc45bea312e0baf91b687e12baabab7dd

2021-06-22 14:14 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function transferFunds(address oldYieldSource, address newYieldSource, uint256 amount) external {
I've refactored it but I wonder if the functions params are named properly.
Here is the commit: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/b7797e189afe0dec22a59cf539c02780f0723306

2021-07-06 16:52 UTC, asselstine requested changes

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +
Initialize the reentrancy guard

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  function _setYieldSource(address newYieldSource) internal {
Function argument types should be specific.  I.e. 

```
function _setYieldSource(IYieldSource newYieldSource) internal {
}
```

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  function setYieldSource(address newYieldSource) external onlyOwnerOrAssetManager returns (bool) {
Make sure to type the arg!  `IYieldSource`

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  function _transferFunds(address _yieldSource, uint256 amount) internal {
Same here `IYieldSource`

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    _depositToken.safeApprove(address(yieldSource), amount);
I think we should do the infinite approval trick here too.  So instead of approving each time we approve once in the constructor, then in the `_setYieldSource` we rescind the approval for the old one and approve the new one.  We'll also need the infinite approval fxn again

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  event YieldSourceSwapped(
This event is redundant, since we have `SwappableYieldSourceSet` and `FundsTransferred`

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    IERC20Upgradeable(_iYieldSource.depositToken()).safeApprove(address(yieldSource), balanceDiff);
We can skip this one too once we infinite approve

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +  function transferFunds(address _yieldSource, uint256 amount) external returns (bool) {
You know what- let's lock this down: `onlyOwnerOrAssetManager`

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    uint256 balanceDiff = _iYieldSource.redeemToken(amount);
Instead of using the balanceDiff; how about we sweep all funds?  It will use a little more gas, but it will allow us to sweep funds that have accrued.

```solidity
_iYieldSource.redeemToken(amount);
uint256 balanceDiff = IERC20(_iYieldSource.depositToken()).balanceOf(address(this));
```

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +    emit YieldSourceSwapped(_currentYieldSource, address(yieldSource));
✂️

2021-07-06 16:52 UTC, asselstine commented on contracts/SwappableYieldSource.sol
> +pragma solidity ^0.7.6;
Let's start locking down the pragma.  No carat here

2021-07-06 16:52 UTC, asselstine commented on contracts/access/AssetManager.sol
> +pragma solidity ^0.7.6;
no carat

2021-07-06 16:52 UTC, asselstine commented on contracts/access/AssetManager.sol
> +abstract contract AssetManager is ContextUpgradeable, OwnableUpgradeable {
This is starting to look like a reusable package!  :)

2021-07-08 18:31 UTC, aodhgan commented on contracts/SwappableYieldSource.sol
> +    (bool succeeded,) = address(_yieldSource).staticcall(abi.encode(_yieldSource.depositToken.selector));
I think we need an `isContract()` to make the staticCall worthwhile. 

as per https://github.com/code-423n4/2021-06-pooltogether-findings/issues/59

2021-07-08 18:34 UTC, aodhgan commented on contracts/SwappableYieldSource.sol
> +    require(_decimals > 0, "SwappableYieldSource/decimals-gt-zero");
Do we also want to check here if the decimals match the underlying asset?

Maybe not since the underlying asset may not have a `decimals()` getter

2021-07-08 18:36 UTC, aodhgan commented on contracts/access/AssetManager.sol
> +        require(assetManager() == _msgSender() || owner() == _msgSender(), "onlyOwnerOrAssetManager: caller is not owner or asset manager");
shorten message.

2021-07-08 18:39 UTC, aodhgan commented on contracts/access/AssetManager.sol
> +        emit AssetManagerTransferred(address(0), newAssetManager);
Why is the first param the zero address when _assetManager can be non zero address?

2021-07-08 18:40 UTC, aodhgan commented on contracts/access/AssetManager.sol
> +     * @notice Set the initial asset manager
Why _initial_? If it is initial there needs to be a `require(_assetManager==0)`

2021-07-08 18:44 UTC, aodhgan commented on package.json
> +    "mainnet-fork": "npm-run-all -p -r \"start-fork\" \"run-fork-parallel\"",
nice

2021-07-08 18:44 UTC, aodhgan commented on package.json
> +    "@pooltogether/pooltogether-contracts": "3.3.7",
trying updating to v3.3.9

2021-07-09 00:17 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +  event SwappableYieldSourceInitialized(
Add natspec `SwappableYieldSourceInitialized` for event variables.
```
@param yieldSource
@param decimals
@param symbol
@param name
@param owner
```

2021-07-09 00:18 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +  event SwappableYieldSourceSet(
Add `SwappableYieldSourceSet` natspec for event variables.
```
@param yieldSource
```

2021-07-09 00:19 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +  event TransferredERC20(
Add `TransferredERC20` natspec for event variables.
```
@param from
@param to
@param amount
@param token
```

2021-07-09 00:28 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +  event FundsTransferred(
Add `FundsTransferred` natspec for event variables.
```
@param yieldSource
@param amount
```

2021-07-09 00:32 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +    require(_decimals > 0, "SwappableYieldSource/decimals-gt-zero");
We avoided doing comparisons in the Pod contract directly as well, but maybe include a verification in the `SwappableYieldSourceFactory.sol` or verify in a frontend responsible for deploying a new `SwappableYieldSource`?

2021-07-09 00:45 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +    require(address(erc20Token) != address(yieldSource), "SwappableYieldSource/yield-source-token-transfer-not-allowed");
The `erc20Token` address should not be compared directly to the `yieldSource` address since the `yieldSource` contract is not the actual ERC20 token.

Instead the `erc20Token`address should be compared to `yieldSource.depositToken()` address.

For example....

`require(address(erc20Token) != yieldSource.depositToken(), "SwappableYieldSource/yield-source-token-transfer-not-allowed");`

2021-07-09 02:53 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +    uint256 shares = 0;
Minor change, but the default is already 0 so you can initialize shares with the following line.

`uint256 shares;`

2021-07-09 02:54 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +    uint256 tokens = 0;
The default is already 0 so you can initialize `tokens` with the following line.

uint256 tokens;

2021-07-09 02:58 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +    uint256 balanceDiff = yieldSource.redeemToken(amount);
Change `balanceDiff` to `balanceRedeemable`?

2021-07-09 03:01 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +    _burnShares(amount);
Even though the function includes `nonReentrant` the best practice is to burn shares before transferring tokens to the user account.

**Recommendation**
Move `_burnShares(amount);` above `uint256 balanceDiff = yieldSource.redeemToken(amount);`

2021-07-09 03:03 UTC, kamescg commented on contracts/SwappableYieldSource.sol
> +  function _requireDifferentYieldSource(address _yieldSource) internal view {
Same comment as Brendan - change address to IYieldSource and update require statement to...

`require(address(_yieldSource) != address(yieldSource), "SwappableYieldSource/same-yield-source");`

2021-07-14 15:01 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/91bbe004f55d7f83071f9caf8ae6f2c0da194841

2021-07-14 15:33 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function _setYieldSource(address newYieldSource) internal {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/1dde88c34362ec0f73fc53929c2e9c41bb9c3bcc

2021-07-14 15:33 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function setYieldSource(address newYieldSource) external onlyOwnerOrAssetManager returns (bool) {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/1dde88c34362ec0f73fc53929c2e9c41bb9c3bcc

2021-07-14 15:33 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function _transferFunds(address _yieldSource, uint256 amount) internal {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/1dde88c34362ec0f73fc53929c2e9c41bb9c3bcc

2021-07-14 15:49 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  event YieldSourceSwapped(
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/1b27be00b00b5a35d622ac03fd47fd1ab7654460

2021-07-14 15:51 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function transferFunds(address _yieldSource, uint256 amount) external returns (bool) {
What's the reasoning behind this? Do you see any attack vector possible by letting this function being callable by anyone?

2021-07-14 16:00 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    emit YieldSourceSwapped(_currentYieldSource, address(yieldSource));
Done: https://github.com/pooltogether/swappable-yield-source/commit/1b27be00b00b5a35d622ac03fd47fd1ab7654460

2021-07-14 16:34 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    uint256 balanceDiff = _iYieldSource.redeemToken(amount);
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/179b90ff547823e7a86d1bd21989623641ea3afc
The redundant `IERC20Upgradeable(_yieldSource.depositToken())` will be removed once we approve the max amount at initialization.

2021-07-14 16:39 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +pragma solidity ^0.7.6;
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/45ae3918cc682b49b85c965e938824f9ae0e604a

2021-07-14 16:39 UTC, PierrickGT commented on contracts/access/AssetManager.sol
> +pragma solidity ^0.7.6;
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/45ae3918cc682b49b85c965e938824f9ae0e604a

2021-07-14 16:42 UTC, PierrickGT commented on contracts/access/AssetManager.sol
> +abstract contract AssetManager is ContextUpgradeable, OwnableUpgradeable {
Should we export it in a common or standalone library?

2021-07-14 16:54 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    require(_decimals > 0, "SwappableYieldSource/decimals-gt-zero");
Yeah, I was wondering how to handle this decimals problem. 
For example, cTokens on Compound have a 8 decimals precision and aToken on Aave have 18 decimals precision.
So let's say we swap cDAI for aDAI, we would go from 8 to 18 decimals but then we can't really update the number of decimals of the SwappableYieldSource token.
Maybe it's best to only allow swappable yield sources to be set with a precision of 18?

2021-07-14 20:40 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function transferFunds(address _yieldSource, uint256 amount) external returns (bool) {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/d40a866acce8675326eb36de6d4b6121bfb2f304

2021-07-14 20:49 UTC, asselstine approved these changes

2021-07-14 21:37 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  event SwappableYieldSourceInitialized(
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/202ae9c9e2dc4f3bf12dcf849b9c16313ce46e68

2021-07-14 21:37 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  event SwappableYieldSourceSet(
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/202ae9c9e2dc4f3bf12dcf849b9c16313ce46e68

2021-07-14 21:37 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  event TransferredERC20(
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/202ae9c9e2dc4f3bf12dcf849b9c16313ce46e68

2021-07-14 21:37 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  event FundsTransferred(
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/202ae9c9e2dc4f3bf12dcf849b9c16313ce46e68

2021-07-14 21:39 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +  function _requireDifferentYieldSource(address _yieldSource) internal view {
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/1dde88c34362ec0f73fc53929c2e9c41bb9c3bcc

2021-07-14 21:42 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    uint256 shares = 0;
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/53c73d18a7589cfb8cde23480fdfcfa6341c95c0

2021-07-14 21:42 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    uint256 tokens = 0;
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/53c73d18a7589cfb8cde23480fdfcfa6341c95c0

2021-07-14 21:55 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    _burnShares(amount);
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/7c3efb364aa0576319ed00a5438a81769a84a284

2021-07-14 21:55 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    uint256 balanceDiff = yieldSource.redeemToken(amount);
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/7c3efb364aa0576319ed00a5438a81769a84a284

2021-07-14 22:24 UTC, PierrickGT commented on contracts/access/AssetManager.sol
> +        require(assetManager() == _msgSender() || owner() == _msgSender(), "onlyOwnerOrAssetManager: caller is not owner or asset manager");
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/268b3f86f83380d98f43596c2e2712793c7a7afc

2021-07-15 15:56 UTC, PierrickGT commented on contracts/access/AssetManager.sol
> +        emit AssetManagerTransferred(address(0), newAssetManager);
Ah yes you're right, I've improved the function to emit a better event when `assetManager` address has been changed:
https://github.com/pooltogether/swappable-yield-source/pull/1/commits/a745c6d6ab51277f3d43eb5a50315ce19605d791

2021-07-15 15:56 UTC, PierrickGT commented on contracts/access/AssetManager.sol
> +     * @notice Set the initial asset manager
Corrected here: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/a745c6d6ab51277f3d43eb5a50315ce19605d791

2021-07-15 20:30 UTC, asselstine approved these changes
Nice!

2021-07-16 22:15 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    (bool succeeded,) = address(_yieldSource).staticcall(abi.encode(_yieldSource.depositToken.selector));
I've improved the function by checking for `address(0)` first and then verifying that the `depositToken` function actually returns an address that is different from `address(0)`.
https://github.com/pooltogether/swappable-yield-source/pull/1/commits/c2eb10221c4353c928baca013454d078cbf02aab

2021-07-19 16:09 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    _depositToken.safeApprove(address(yieldSource), amount);
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/c06a2305c47872ac8762d5edfb5193e123fed4e3

2021-07-19 16:09 UTC, PierrickGT commented on contracts/SwappableYieldSource.sol
> +    IERC20Upgradeable(_iYieldSource.depositToken()).safeApprove(address(yieldSource), balanceDiff);
Done: https://github.com/pooltogether/swappable-yield-source/pull/1/commits/c06a2305c47872ac8762d5edfb5193e123fed4e3

2021-07-19 16:19 UTC, PierrickGT commented on package.json
> +    "@pooltogether/pooltogether-contracts": "3.3.7",
There is no `artefacts` export in new versions, I have to use version `3.3.8` for my mainnet fork tests to work.
https://github.com/pooltogether/swappable-yield-source/pull/1/commits/c2eb10221c4353c928baca013454d078cbf02aab#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R35

2021-07-21 16:52 UTC, aodhgan commented on contracts/access/AssetManager.sol
> +abstract contract AssetManager is ContextUpgradeable, OwnableUpgradeable {
Likely a repo similar to https://github.com/pooltogether/pooltogether-generic-registry where it can be imported into other projects as an npm package. Would say doesn't need to be done for this PR, but more afterwards as a small project.

2021-07-21 16:59 UTC, aodhgan commented on contracts/SwappableYieldSource.sol
> +    require(_decimals > 0, "SwappableYieldSource/decimals-gt-zero");
Does it matter since the `decimals` here are solely for internal accounting and in your above example (cToken to aToken) they would have a different `balances[address => uint256]` entry so it wouldn't affect the `tokenToShares()` and `sharesToToken()`?

@asselstine

2021-07-28 21:39 UTC, merged